[project]
id = "paestro-google-workspace-mcp"

[environments.production]
name = "production"

[deploy]
startCommand = "python main.py --transport streamable-http"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3