[project]
id = "paestro-google-workspace-mcp"

[environments.production]
name = "production"

[deploy]
startCommand = "python fastmcp_server.py --transport streamable-http --tools sheets"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3